name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: pdflatex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: bibtex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.aux
          compiler: bibtex
          args: 
      - name: pdflatex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: example-minimal
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.tex
          compiler: lualatex
          args: -interaction=nonstopmode -shell-escape
      - name: Commit changes
        uses: EndBug/add-and-commit@v8
        with:
          author_name: AuthorNameHere
          author_email: author_email_here@email.com
          message: 'Auto-updating PDF File'
          add: 'main.pdf'
